import { CONST_ASSETS } from '@/lib/preloader';

const CONST_SKILL01_IMG = CONST_ASSETS.IMAGES.SKILL_1;
const CONST_SKILL02_IMG = CONST_ASSETS.IMAGES.SKILL_2;
const CONST_SKILL03_IMG = CONST_ASSETS.IMAGES.SKILL_3;
const CONST_SKILL04_IMG = CONST_ASSETS.IMAGES.SKILL_4;
const CONST_SOUND_SPELL_CAST = CONST_ASSETS.SOUNDS.SPELL_CAST;
const CONST_SOUND_SPELL_IMPACT = CONST_ASSETS.SOUNDS.SPELL_IMPACT;
const CONST_SOUND_SWORD_CAST = CONST_ASSETS.SOUNDS.SWORD_CAST;
const CONST_SOUND_SWORD_IMPACT = CONST_ASSETS.SOUNDS.SWORD_IMPACT;

export type Skill = {
    id: number;
    name: string;
    icon: string;

    cooldown: number;
    energyCost: number;
    castTime: number;

    castSound: string;
    impactSound: string;

    damage: number;
    heal: number;
    stun: number;
    recover: number;
    shield: number;
    interrupt: number;
};

export type ElementKey = "As" | "Br" | "Ga" | "Kr" | "Li" | "Zn";

export const skillSets: Record<ElementKey, Skill[]> = {
    As: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
    Br: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
    Ga: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
    Kr: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
    Li: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
    Zn: [
        {
            id: 1,
            name: "Légère",
            icon: CONST_SKILL01_IMG,
            cooldown: 0.25,
            energyCost: 0,
            castTime: 0,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 2,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 2,
            name: "Lourde",
            icon: CONST_SKILL02_IMG,
            cooldown: 0.25,
            energyCost: 10,
            castTime: 1,
            castSound: CONST_SOUND_SWORD_CAST,
            impactSound: CONST_SOUND_SWORD_IMPACT,
            damage: 5,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 3,
            name: "Contrôle",
            icon: CONST_SKILL03_IMG,
            cooldown: 0.25,
            energyCost: 20,
            castTime: 2,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 10,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
        {
            id: 4,
            name: "Ultime",
            icon: CONST_SKILL04_IMG,
            cooldown: 0.25,
            energyCost: 30,
            castTime: 3,
            castSound: CONST_SOUND_SPELL_CAST,
            impactSound: CONST_SOUND_SPELL_IMPACT,
            damage: 15,
            heal: 0,
            stun: 0,
            recover: 0,
            shield: 0,
            interrupt: 0,
        },
    ],
};